{
 "title": "DS412+",
 "description": "Monitorizacion de mi Synology",
 "tags": [
  "synology",
  "nas"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Estado",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(diskStatus1) AS \"Disco1\",\n  avg(diskStatus2) AS \"Disco2\",\n  avg(diskStatus3) AS \"Disco3\",\n  avg(diskStatus4) AS \"Disco4\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Espacio libre",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  raidFreeSize AS \"Libre\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "DS412+",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(systemStatus) AS \"systemStatus\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Ram libre",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  memAvailFree AS \"Libre\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(temperature) AS \"temperature\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Bateria",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(upsBatteryChargeValue) AS \"upsBatteryChargeValue\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Carga APC",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(upsInfoLoadValue) AS \"upsInfoLoadValue\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Usuarios",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  users AS \"users\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "HDs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  diskTemperature1 AS \"HGST 1\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nORDER BY fecha"
    },
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  diskTemperature2 AS \"HGST 2\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nORDER BY fecha"
    },
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  diskTemperature3 AS \"Disco 3\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nORDER BY fecha"
    },
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  diskTemperature4 AS \"Disco 4\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(ssCpuTotal) AS \"CPU\"\nFROM medidas\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  },
  {
   "title": "Red",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,5s),\n  ifHCInOctets / 5 AS \"In\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,5s)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,5s),\n  ifHCOutOctets / 5 AS \"Out\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,5s)"
    }
   ]
  },
  {
   "title": "Carga Volumen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fecha,$__interval),\n  avg(spaceIOLA) AS \"Carga\"\nFROM medidas\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY $__timeGroup(fecha,$__interval)"
    }
   ]
  }
 ]
}